name: flutter_freedome_player
description: "Flutter plugin for playing 3D/AR/VR content and various media formats including .comics, .boranko, collada and others. Supports both screen display and dome projections."
version: 1.0.1
homepage: https://github.com/FreeDome/flutter_freedome_player
repository: https://github.com/FreeDome/flutter_freedome_player
issue_tracker: https://github.com/FreeDome/flutter_freedome_player/issues
documentation: https://github.com/FreeDome/flutter_freedome_player#readme
license: NativeMindNONC

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  
  # 3D and AR dependencies
  flutter_3d_controller: ^2.2.0
  model_viewer_plus: ^1.9.3
  # ar_flutter_plugin: ^0.7.3  # Will be enabled when namespace issues are resolved
  vector_math: ^2.1.4
  
  # File handling and parsing
  xml: ^6.5.0
  archive: ^3.4.10
  path: ^1.8.3
  
  # HTTP and networking
  http: ^1.1.0
  
  # State management
  provider: ^6.1.1
  
  # Utilities
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_freedome_player
        pluginClass: FlutterFreedomePlayerPlugin
      ios:
        pluginClass: FlutterFreedomePlayerPlugin
      linux:
        pluginClass: FlutterFreedomePlayerPlugin
      macos:
        pluginClass: FlutterFreedomePlayerPlugin
      web:
        pluginClass: FlutterFreedomePlayerPlugin
        fileName: flutter_freedome_player_web.dart
      windows:
        pluginClass: FlutterFreedomePlayerPlugin

topics:
  - three-d
  - augmented-reality
  - virtual-reality
  - multimedia
  - dome-projection